### ISSUE TITLE
name map notation

### ISSUE THREAD

**Issue by lisp** [fraunhoferfokus/RDFRuleStreams#11]
in the namedPart definition

    namedPart(DS) = Associativeorder(DS)(names(DS), nameMap(DS)(names(DS)) ∪ {DEFAULT => {} })

which uses 

    S => M(S) = {n => M(n) | n ∈ S} denotes the restriction of a mapping M to a set S ⊆ dom(M).

?
the notation looks like the same as when the name map applies to a name.
if a subscript would be appropriate for the restriction is would communicate the distinction.

**Comment by greenTara** [comment]
It should have been

 namedPart(DS) = Associativeorder(DS)(names(DS), names(DS) =>nameMap(DS)(names(DS)) ∪ {DEFAULT => {} })

But even that is not really mathematically correct.

I will try to find out what is the proper notation for the restriction of a mapping.

**Comment by greenTara** [comment]
OK, this notation is 

M|<sub>S</sub>

**Comment by greenTara** [comment]
resolved with commit 9474545c588c50329f871269da1b717249522936
