### ISSUE TITLE
defintion table notation ::< , ::=

### ISSUE THREAD

**Issue by lisp** [fraunhoferfokus/RDFRuleStreams#12]
- what do the paired entries for ::< and ::? indicate

- solitary-associationk ∩ "association-tree" : should be "associative-tree" ?

- is "[2^RDF-Name, Total-Order(RDF-Name)]" the same as  2^RDF-Name+, that is, the power set of sequences?

**Comment by greenTara** [comment]
* ::< means the datatype is a subtype of the composition
* yes, I will correct that type
* not quite. the former is an (awkward) notation for ordered sets, which differ from sequences by not allowing duplicate entries. I will look around to see if there is a better notation for that.

**Comment by greenTara** [comment]
The set of all ordered subsets of D is known as the set of all partial permutations D and is denoted as ℘℘(D)
