### ISSUE TITLE
notation description

### ISSUE THREAD

**Issue by lisp** [fraunhoferfokus/RDFRuleStreams#13]
the terms Assoc_k, Associative_k, and associative confuse as it is not clear which are functions, which are types.

**Comment by greenTara** [comment]
Yes, it is a problem.
* Assoc_k defines types
* Associative_k is a constructor of things of Assoc_k type
* associative... are names of particular types

Some thoughts:
* Assoc_k   becomes TypeAssoc_k, and similarly with the other type defining functions
* Associative_k becomes Associative-INIT_k, and similarly with the other constructors
* associative ... stays the same.
