### ISSUE TITLE
3.3.2 : associative definition

### ISSUE THREAD

**Issue by lisp** [fraunhoferfokus/RDFRuleStreams#14]
in "[k, N, M]", is N always non-empty?
that is, is

    [1, {}, {DEFAULT=> [0, {}, {DEFAULT => G} ] ]

a valid order one associative?

**Comment by greenTara** [comment]
For k>0, N has to be nonempty.

**Comment by greenTara** [comment]
For k=0, N must be empty.

**Comment by greenTara** [comment]
closed by mistake
