### ISSUE TITLE
3.3.3 equivalence to named graph

### ISSUE THREAD

**Issue by lisp** [fraunhoferfokus/RDFRuleStreams#16]
in

> A named graph may be emulated as a first-order associative tree that is also a solitary association.
> A k-th order solitary association tree is a k-th order associative tree that is also a solitary association.

switch the order and describe the named graph as a "first-order solitary association tree"?

is the intended term "solitary association tree" or "solitary associative tree"?

**Comment by greenTara** [comment]
I intended to use solitary association tree, although it might be more clear as solitary-association tree or even tree-solitary-association, that is, a solitary association that is also an associative tree.

Mathematically speaking, it is not correct to say that a named graph *is* a first-order associative tree. That is why I use *emulated*.

**Comment by greenTara** [comment]
Oh, I think i see what you are suggesting:

A k-th order solitary-association tree is a k-th order associative tree that is also a solitary association.
A named graph may be emulated as a first-order solitary-association tree.

**Comment by lisp** [comment]
yes
