### ISSUE TITLE
3.4.1 use "DST" or "DS" as the element term

### ISSUE THREAD

**Issue by lisp** [fraunhoferfokus/RDFRuleStreams#18]

**Comment by greenTara** [comment]
It would be a good idea to use a naming convention for these metavariables to indicate type, and declare these in a table.

How about:
* E for general entity
* DST for data structure
* DS for RDF Dataset
* DSQ for data sequence
* SQ for a sequence of something other than data structures
* MDST for multivalent data structure
* VDST for versioned data structure
* ADST for associative data structure
* AT for associative tree
* SO for solitary association
* SOT for solitary association-tree
* R for repository
* STR for store
* n or name for names
* M for name mappings
* VI, SI for ordered sets (I for index)
* G for graphs
* others?

**Comment by lisp** [comment]
once it involves a structure, always leave the "T" there.
- MDST for multivalent data structure
- VDST for versioned data structure
- ADST for associative data structure
