### ISSUE TITLE
3.4.1 : blank node semantics

### ISSUE THREAD

**Issue by lisp** [fraunhoferfokus/RDFRuleStreams#22]
in
>Note that by the definition of OpInsertData in [SPARQL11-Update], any blank node appearing in P' that also appears in P must be renamed.

allow for variant blank node surfaces by qualifyinf 1.1 semantics as a special case.

**Comment by greenTara** [comment]
this will be resolved by adding an editorial note that there is  a need for a similar operator that does not rename blank nodes. There is a corresponding dichotomy with merge and union of datasets.
