### ISSUE TITLE
Decouple order in repositories with order in store/

### ISSUE THREAD

**Issue by greenTara** [fraunhoferfokus/RDFRuleStreams#27]
Consider the possibility that the requirement for the order of version in the repositories of stores be in harmony with the order of the store could be dropped. If it is not required, then the order in the store versions would be take precedent. In this way you could impose a different order on a repository, e.g. as a different perspective on it, without having to create a new repository.

**Comment by greenTara** [comment]
Some points that would have to be cleared up to make this work: 
* when the operation is performed to restrict a store to a particular repository (e.g. with the function content applied to the associative part of the store), does this return the repository with the original version order or with the modified order as expressed in the store?
* when a store transformation is defined, it has to be sorted out which repositories from the input store are used - the original ones or the "virtual" ones ordered according to the store version order.

**Comment by lisp** [comment]
the issue arises already with bi-temporality.
as soon as the predicate timestamp changes, the effective order could change.
(should i open a distinct issue for bi-temporality?)

**Comment by greenTara** [comment]
Although they are related, it probably makes sense to have a separate issue for that.

**Comment by lisp** [comment]
> when a store transformation is defined, it has to be sorted out which repositories from the input store are used - the original ones or the "virtual" ones ordered according to the store version order.

there is no obvious answer to that one.
if this is to behave analogous to order-one associative trees (aka datasets with named graphs), then the same content would appear with a different name. - or order index.

**Comment by greenTara** [comment]
We could provide access to both views of the repository, e.g. with functions originalAssociativePart and virtualAssociativePart (or some better names). and similar define store transformations that work on one versus the other. It may become clear with use whether one or the other is more useful.

**Comment by greenTara** [comment]
highest priority

**Comment by greenTara** [comment]
The extended constructor Store-INIT has now been defined that takes as input non-monotonic mappings from store versions to repository versions. commit 42d1e80f0de4ab6d1a36be46c91a6b19c3eba59c

**Comment by greenTara** [comment]
Still to be done:
1. address constraints on the non-monotonic mapping (it must define a permutation of the repository versions)
2. address access to the "original" repositories
  - the treatment so far is that the permuted repositories are the "repositories of the store" and the original repositories are something else. The StoreTransformation operator will work abstractly on the permuted repositories, but can be implemented to work on the original repositories if they are available.
