### ISSUE TITLE
3.3.3 : correction and alternative term

### ISSUE THREAD

**Issue by lisp** [fraunhoferfokus/RDFRuleStreams#30]
solitary associative tree, without qualificatin

- without qualification
- solitary associative tree -> "solitary tree" ?

**Comment by greenTara** [comment]
I considered using this term, but it seems misleading to me. The solitary-association-tree is not any more solitary, as a tree, than other associative trees. What is solitary is the (name) association within the tree. So I have started using "solitary-association-tree", but it is long and unwieldy. I'm willing to consider other terms.
